ARG RUST_IMAGE=rust:1.98.0-bookworm
ARG RUNTIME_IMAGE=debian
ARG RUNTIME_ID=88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171

FROM ${RUST_IMAGE} AS builder
WORKDIR /workspace
COPY . ./
RUN cargo build --locked --release --package omarchy-quickshare

FROM ${RUNTIME_IMAGE}@sha256:${RUNTIME_ID} AS runtime
RUN groupadd --system quickshare \
    && useradd --system --gid quickshare --create-home quickshare
COPY --from=builder /workspace/target/release/omarchy-quickshare \
  /usr/local/bin/omarchy-quickshare
USER quickshare
ENTRYPOINT ["/usr/local/bin/omarchy-quickshare"]
