use std::{
    env, fs,
    path::{Path, PathBuf},
};

const NEARBY_INPUTS: &[&str] = &[
    "connections/implementation/proto/offline_wire_formats.proto",
    "proto/sharing_enums.proto",
    "sharing/proto/enums.proto",
    "sharing/proto/wire_format.proto",
];
const UKEY2_INPUTS: &[&str] = &[
    "device_to_device_messages.proto",
    "securegcm.proto",
    "securemessage.proto",
    "ukey.proto",
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?)
        .ancestors()
        .nth(3)
        .ok_or("code generator must run below the repository root")?
        .to_path_buf();
    let nearby = root.join(".cache/test-env/sources/trees/google-nearby");
    let ukey2 =
        root.join(".cache/test-env/sources/trees/google-ukey2/src/main/proto");
    let output = root.join("crates/core/wire/src/generated");
    fs::create_dir_all(&output)?;
    let nearby_inputs = input_paths(&nearby, NEARBY_INPUTS);
    let ukey2_inputs = input_paths(&ukey2, UKEY2_INPUTS);
    let mut inputs = nearby_inputs;
    inputs.extend(ukey2_inputs);
    let mut config = prost_build::Config::new();
    config.out_dir(&output);
    config.compile_protos(&inputs, &[nearby, ukey2])?;
    add_provenance(&output)?;
    Ok(())
}

fn input_paths(root: &Path, inputs: &[&str]) -> Vec<PathBuf> {
    inputs.iter().map(|input| root.join(input)).collect()
}

fn add_provenance(output: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let header = "// Generated by tools/codegen/quickshare-wire.\n";
    let sources = "upstream/sources.toml#google-nearby, google-ukey2";
    let header = format!("{header}// Inputs: {sources}.\n\n");
    for entry in fs::read_dir(output)? {
        let path = entry?.path();
        if path.extension().is_some_and(|extension| extension == "rs") {
            let generated = rustdoc_safe(compatible_connections_schema(
                &path,
                fs::read_to_string(&path)?,
            )?);
            fs::write(path, format!("{header}{generated}"))?;
        }
    }
    Ok(())
}

fn rustdoc_safe(generated: String) -> String {
    generated.replace("<TYPE>", "`TYPE`").replace(
        "#[allow(deprecated)]",
        concat!(
            "#[allow(deprecated, reason = ",
            "\"prost references deprecated enum variants\")]"
        ),
    )
}

fn compatible_connections_schema(
    path: &Path,
    generated: String,
) -> Result<String, Box<dyn std::error::Error>> {
    if path.file_name().and_then(|name| name.to_str())
        != Some("location.nearby.connections.rs")
    {
        return Ok(generated);
    }
    let original = concat!(
        "    #[prost(string, optional, tag = \"2\")]\n",
        "    pub endpoint_name: ",
        "::core::option::Option<::prost::alloc::string::String>,",
    );
    let replacement = concat!(
        "    #[prost(bytes = \"vec\", optional, tag = \"2\")]\n",
        "    pub endpoint_name: ",
        "::core::option::Option<::prost::alloc::vec::Vec<u8>>,",
    );
    if !generated.contains(original) {
        return Err("generated Connections endpoint_name shape changed".into());
    }
    Ok(generated.replacen(original, replacement, 1))
}
