import { isUtf8 } from "node:buffer";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { configurationFailures } from "./structure-configuration.mjs";
import { output, run } from "./lib/process.mjs";

export { configurationFailures } from "./structure-configuration.mjs";

const SCRIPT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const ROOT = resolve(process.env.GATE_ROOT ?? SCRIPT_ROOT);
const EXCLUDED_NAMES = new Set([
  ".cache",
  ".codegraph",
  ".git",
  "dist",
  "node_modules",
  "reports",
  "target",
]);
const GENERATED_FILES = new Set(["Cargo.lock", "package-lock.json"]);
const GENERATED_RUST = [
  {
    generator: "// Generated by tools/codegen/quickshare-wire.",
    inputs: "// Inputs: upstream/sources.toml#google-nearby, google-ukey2.",
    prefix: "crates/core/wire/src/generated/",
  },
];
GENERATED_FILES.add(
  "tests/environments/android/probe/gradle/verification-metadata.xml",
);
const DIRECTORY_INDEXES = new Set(["crates", "tests/fixtures", "tests/suites"]);
const APPLICATION_PREFIXES = [
  "crates/",
  "fuzz/",
  "packaging/",
  "rules/ast-grep/",
];
const APPLICATION_FILES = new Set([
  "Cargo.lock",
  "Cargo.toml",
  "clippy.toml",
  "rust-toolchain.toml",
  "rustfmt.toml",
  "sgconfig.yml",
]);
const PROJECT_LINE_LIMIT = 500;
const TEST_LINE_LIMIT = 800;
const DIRECTORY_CHILD_LIMIT = 12;
const CODE_LINE_LIMIT = 80;
const FUNCTION_LINE_LIMIT = 50;
const AST_GREP = resolve(
  process.env.AST_GREP ?? join(SCRIPT_ROOT, "node_modules/.bin/ast-grep"),
);
const CODE_EXTENSION = /\.(?:cjs|js|mjs|py|pyi|qml|rs|sh)$/u;
const NATIVE_EXTENSION = /\.(?:c|cc|cpp|cxx|h|hh|hpp|hxx|inl|ipp)$/u;
const JVM_EXTENSION = /\.(?:java|kt|kts)$/u;
const BUILD_EXTENSION = /\.(?:bazel|bzl|dockerfile)$/u;
const BUILD_FILE =
  /(?:^|\/)(?:BUILD(?:\.bazel)?|Dockerfile(?:\.[^/]+)?|MODULE\.bazel)$/u;
const BASH_SHEBANG = /^#!.*(?:\/|\s)bash(?:\s|$)/u;
const LINE_BREAK_PATTERN = /\n/gu;
const TEST_FILE_PATTERN = /(?:^|\.)test\.[^.]+$/u;
const PYTHON_EXTENSION_PATTERN = /\.pyi?$/u;
const CPP_EXTENSION_PATTERN = /\.(?:cc|cpp|cxx|h|hh|hpp|hxx|inl|ipp)$/u;
const KOTLIN_EXTENSION_PATTERN = /\.kts?$/u;
const FUNCTION_KINDS = new Map([
  ["bash", ["function_definition"]],
  ["c", ["function_definition"]],
  ["cpp", ["function_definition"]],
  ["java", ["method_declaration", "constructor_declaration"]],
  ["kotlin", ["function_declaration", "secondary_constructor"]],
  ["python", ["function_definition"]],
  ["qml", ["function_declaration"]],
]);

function walkFiles(directory, base = directory) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (!EXCLUDED_NAMES.has(entry.name) && entry.name !== "_") {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) {
        files.push(...walkFiles(absolute, base));
      }
      if (entry.isFile()) {
        files.push(relative(base, absolute).split(sep).join("/"));
      }
    }
  }
  return files;
}

function repositoryFiles() {
  if (!existsSync(join(ROOT, ".git"))) {
    return walkFiles(ROOT);
  }
  const listed = output(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard", "-z"],
    { cwd: ROOT },
  );
  if (listed) {
    return listed.split("\0").filter(Boolean);
  }
  return [];
}

function physicalLines(path) {
  const bytes = readFileSync(path);
  if (bytes.includes(0) || !isUtf8(bytes)) {
    return null;
  }
  const source = bytes.toString("utf8");
  if (!source) {
    return 0;
  }
  const lineBreaks = source.match(LINE_BREAK_PATTERN)?.length ?? 0;
  let finalLine = 1;
  if (source.endsWith("\n")) {
    finalLine = 0;
  }
  return lineBreaks + finalLine;
}

export function lineLimit(path) {
  const isTest =
    path.startsWith("tests/") ||
    path.includes("/tests/") ||
    TEST_FILE_PATTERN.test(path);
  if (isTest) {
    return TEST_LINE_LIMIT;
  }
  return PROJECT_LINE_LIMIT;
}

function generatedRustProvenance(path) {
  if (!path.endsWith(".rs")) {
    return null;
  }
  return GENERATED_RUST.find(({ prefix }) => path.startsWith(prefix)) ?? null;
}

export function isGenerated(path) {
  return (
    GENERATED_FILES.has(path) ||
    generatedRustProvenance(path) !== null ||
    path.startsWith("rules/ast-grep/schemas/")
  );
}

export function generatedProvenanceFailures(files, options = {}) {
  const root = options.root ?? ROOT;
  const failures = [];
  for (const path of files) {
    const provenance = generatedRustProvenance(path);
    if (provenance) {
      const source = readFileSync(join(root, path), "utf8");
      const header = [provenance.generator, provenance.inputs, ""].join("\n");
      if (!source.startsWith(provenance.generator)) {
        failures.push(`${path}: missing generator provenance header`);
      } else if (!source.startsWith(header)) {
        failures.push(`${path}: missing pinned input provenance`);
      }
    }
  }
  return failures;
}

export function structureScope(path) {
  if (
    APPLICATION_FILES.has(path) ||
    APPLICATION_PREFIXES.some((prefix) => path.startsWith(prefix))
  ) {
    return "app";
  }
  return "tooling";
}

export function lineBudgetFailures(files) {
  const failures = [];
  for (const path of files) {
    if (!isGenerated(path)) {
      const absolute = join(ROOT, path);
      if (existsSync(absolute) && statSync(absolute).isFile()) {
        const limit = lineLimit(path);
        const lines = physicalLines(absolute);
        if (lines !== null && lines > limit) {
          failures.push(`${path}: ${lines} lines (limit ${limit})`);
        }
      }
    }
  }
  return failures;
}

function isMakefile(path) {
  return path === "Makefile" || path.endsWith("/Makefile");
}

function isBashFile(path, source) {
  return path.endsWith(".sh") || BASH_SHEBANG.test(source);
}

function isCodeFile(path, source) {
  return (
    CODE_EXTENSION.test(path) ||
    NATIVE_EXTENSION.test(path) ||
    JVM_EXTENSION.test(path) ||
    BUILD_EXTENSION.test(path) ||
    BUILD_FILE.test(path) ||
    isMakefile(path) ||
    isBashFile(path, source)
  );
}

function functionLanguage(path, source) {
  if (isBashFile(path, source)) {
    return "bash";
  }
  if (PYTHON_EXTENSION_PATTERN.test(path)) {
    return "python";
  }
  if (path.endsWith(".c")) {
    return "c";
  }
  if (CPP_EXTENSION_PATTERN.test(path)) {
    return "cpp";
  }
  if (path.endsWith(".java")) {
    return "java";
  }
  if (KOTLIN_EXTENSION_PATTERN.test(path)) {
    return "kotlin";
  }
  if (path.endsWith(".qml")) {
    return "qml";
  }
  return null;
}

export function codeLineFailures(path, source) {
  if (!isCodeFile(path, source)) {
    return [];
  }
  const failures = [];
  for (const [index, line] of source.split("\n").entries()) {
    const { length } = [...line];
    if (length > CODE_LINE_LIMIT) {
      failures.push(
        `${path}:${index + 1}: ${length} columns (limit ${CODE_LINE_LIMIT})`,
      );
    }
  }
  return failures;
}

function functionMatchFailure(match, language, reportedFile) {
  const start = match.range.start.line;
  const lines = match.range.end.line - start + 1;
  if (lines <= FUNCTION_LINE_LIMIT) {
    return [];
  }
  const path = reportedFile ?? match.file;
  return [
    `${path}:${start + 1}: ${language} function has ${lines} lines ` +
      `(limit ${FUNCTION_LINE_LIMIT})`,
  ];
}

function astFunctionFailures(specification, options) {
  const { files, input, kind, language, reportedFile } = specification;
  if (!files.length) {
    return [];
  }
  const root = options.root ?? ROOT;
  const astGrep = options.astGrep ?? AST_GREP;
  let parserLanguage = language;
  if (language === "qml") {
    parserLanguage = "javascript";
  }
  const astArguments = [
    "run",
    "--kind",
    kind,
    "--lang",
    parserLanguage,
    "--json=stream",
  ];
  astArguments.push(...files);
  const result = run(astGrep, astArguments, {
    allowFailure: true,
    capture: true,
    cwd: root,
    input,
    quiet: true,
  });
  const errorDetail = result.stderr.trim();
  if (result.status > 1 || errorDetail) {
    const detail = errorDetail || `ast-grep exited with ${result.status}`;
    throw new Error(detail);
  }
  const matches = result.stdout.trim();
  if (!matches) {
    return [];
  }
  return matches
    .split("\n")
    .map((line) => JSON.parse(line))
    .flatMap((match) => functionMatchFailure(match, language, reportedFile));
}

export function functionSpanFailures(filesByLanguage, options = {}) {
  const failures = [];
  for (const [language, files] of filesByLanguage) {
    const kinds = FUNCTION_KINDS.get(language) ?? [];
    for (const kind of kinds) {
      if (language === "qml") {
        const root = options.root ?? ROOT;
        for (const path of files) {
          const input = readFileSync(join(root, path), "utf8");
          const specification = {
            files: ["--stdin"],
            input,
            kind,
            language,
            reportedFile: path,
          };
          failures.push(...astFunctionFailures(specification, options));
        }
      } else {
        failures.push(
          ...astFunctionFailures({ files, kind, language }, options),
        );
      }
    }
  }
  return failures;
}

export function codeMetricFailures(files) {
  const failures = [];
  const filesByLanguage = new Map();
  for (const path of files) {
    if (!isGenerated(path)) {
      const absolute = join(ROOT, path);
      if (existsSync(absolute) && statSync(absolute).isFile()) {
        const source = readFileSync(absolute, "utf8");
        failures.push(...codeLineFailures(path, source));
        const language = functionLanguage(path, source);
        if (language) {
          const languageFiles = filesByLanguage.get(language) ?? [];
          languageFiles.push(path);
          filesByLanguage.set(language, languageFiles);
        }
      }
    }
  }
  return [...failures, ...functionSpanFailures(filesByLanguage)];
}

function isDirectoryIndex(directory) {
  if (directory === ".") {
    return DIRECTORY_INDEXES.has("");
  }
  return DIRECTORY_INDEXES.has(directory);
}

export function directoryBudgetFailures(files) {
  const contents = new Map();
  for (const path of files) {
    const parts = path.split("/");
    for (let index = 0; index < parts.length; index += 1) {
      let directory = parts.slice(0, index).join("/");
      if (!directory) {
        directory = ".";
      }
      const child = parts[index];
      let kind = "directories";
      if (index === parts.length - 1) {
        kind = "files";
      }
      const entry = contents.get(directory) ?? {
        files: new Set(),
        directories: new Set(),
      };
      entry[kind].add(child);
      contents.set(directory, entry);
    }
  }

  const failures = [];
  for (const [directory, entry] of contents) {
    if (directory !== "." && entry.files.size > DIRECTORY_CHILD_LIMIT) {
      failures.push(
        `${directory}: ${entry.files.size} direct files (limit 12)`,
      );
    }
    if (
      entry.directories.size > DIRECTORY_CHILD_LIMIT &&
      !isDirectoryIndex(directory)
    ) {
      failures.push(
        `${directory}: ${entry.directories.size} direct directories (limit 12)`,
      );
    }
  }
  return failures;
}

export async function checkStructure(scope = "all") {
  if (!["all", "app", "tooling"].includes(scope)) {
    throw new Error(`unknown structure scope: ${scope}`);
  }
  let files = repositoryFiles();
  if (scope !== "all") {
    files = files.filter((path) => structureScope(path) === scope);
  }
  return [
    ...generatedProvenanceFailures(files),
    ...lineBudgetFailures(files),
    ...directoryBudgetFailures(files),
    ...codeMetricFailures(files),
    ...(await configurationFailures()),
  ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const scope = process.argv[2] ?? "all";
  const failures = await checkStructure(scope);
  if (failures.length) {
    process.stderr.write(`${failures.join("\n")}\n`);
    process.exitCode = 1;
  } else {
    process.stdout.write(`Repository ${scope} structure contracts passed.\n`);
  }
}
