load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "peer_connection_interface",
    hdrs = ["peer_connection_interface.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "scoped_refptr",
    hdrs = ["scoped_refptr.h"],
    visibility = ["//visibility:public"],
)
