[package]
name = "quickshare-network"
version = "0.0.0"
description = "Linux network media for Quick Share"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
if-addrs.workspace = true
mdns-sd.workspace = true
zbus.workspace = true

[lints]
workspace = true
